### ISSUE TITLE
Trello Board of Ideas

### ISSUE THREAD

**Issue by distracteddev** [nodejs/docs#1]
The following is a transcription of the topics discussed at NodeConf. This board will serve as the backlog proposed documentation improvements. The list is _not_ prioritized. As the efforts are prioritized, they will be converted into Github issues which can then be assigned to individuals and implemented.

https://trello.com/b/OK2TBRw1/node-js-documentation-brainstorm

Note: The board can be viewed by anyone but I will have to individually add people in order to grant "Edit" permissions. If you would like to add or edit the board, please leave your email below or email me at zeus@lever.co and I will add you as a collaborator immediately.

**Comment by danielkhan** [comment]
Reviewing the Trello board and looking at actionable items for me I started to wonder if there is some kind of styleguide or a "getting started writing docs for nodejs" doc available.
I mean - if I want to start my first doc today how do I do that?

**Comment by Qard** [comment]
There's not really a formal style guide for docs, as far as I'm aware. It should be fine to just approximate the style of the markdown docs in https://github.com/nodejs/io.js/tree/master/doc/api. Structural aspects will likely vary from existing content, and I suspect we'll just gradually converge on a defined style over time.

I think it's best that people just start making PRs with some content and we can provide feedback as more comes in.

**Comment by chrisdickinson** [comment]
Hey – I'm the blocker on this for now – I'm going to try and get the style guide / values guide done as fast as I can so we have a solid ground for things. The mechanical part of the style guide will likely look a lot like the guide in the core repo, as @Qard notes, especially when it pertains to reference documentation.

The associated issue is #4.

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
