### ISSUE TITLE
List of Documentation Issues to Be Worked on from nodejs/iojs.org (formerly iojs/website)

### ISSUE THREAD

**Issue by bnb** [nodejs/docs#10]
I have tagged issues from the old iojs/website repo, now located at nodejs/iojs.org, with docs and invalid to indicate that they should be handled by the Docs WG, and removed them from the new.nodejs.org agenda. 

**These issues are still important, and need to be addressed.** They just aren't in the perfect place to do so - thus, this issue has been created.

List: [node/iojs.org - issues tagged with "docs"](https://github.com/nodejs/iojs.org/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Adocs)

These issues are something that I think can be taken care of by the Docs WG. Feel free to pull these into an issue or PR in this repo - if you do, though, make sure you link the issue in nodejs/iojs.org you're working from.

**Comment by stringparser** [comment]
@nodejs/iojs-es, concerning API docs and open questions about API localization docs. 
EDIT: Related to #11

**Comment by ungoldman** [comment]
Looks like every issue in the list linked to above ([node/iojs.org - issues tagged with "docs"](https://github.com/nodejs/iojs.org/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Adocs)) is now closed. Is it safe to assume this issue can be closed too?

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
