### ISSUE TITLE
[debugger] incorrect information about connecting to process

### ISSUE THREAD

**Issue by trevnorris** [nodejs/docs#103]
In the debugger docs, under "Advanced Usage" it states:

> An alternative way of enabling and accessing the debugger is to start Node.js with the `--debug` command-line flag or by signaling an existing Node.js process with `SIGUSR1`.
> 
> Once a process has been set in debug mode this way, it can be connected to using the Node.js debugger...

This implies that one must start with the `--debugger` flag or signal using `SIGUSR1` before it's possible to connect to the process using the debugger. This is in fact false when it comes to connecting to the process via pid. It's possible to connect to any node process, at least back to v4.

The docs should be changed to mention that it's always possible to connect to a node process via pid.

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
