### ISSUE TITLE
ChildProcess.unref() documentation is absent.

### ISSUE THREAD

**Issue by Dzenly** [nodejs/docs#104]
The unref() function of the ChildProcess class is mentioned here and there in the child_process documentation (https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_class_childprocess). But there is not a separate description of this function, so child.unref() is absent in the table of contents.

**Comment by sam-github** [comment]
Agreed, should be documented.

**Comment by eljefedelrodeodeljefe** [comment]
Do you care for a PR? I agree.

**Comment by Dzenly** [comment]
I feel some enthusiasm and I have some time, but I don't have a crystal-clear understanding what exactly does unref() do.

Doc says: 

> Doing so will cause the parent's event loop to not include the child in its reference count, allowing the parent to exit independently of the child, unless there is an established IPC channel between the child and parent.

uv.h contains such a comment:

> Note that the child process will still keep the parent's event loop alive unless the parent process calls uv_unref() on the child's process handle.

So I have a question:
What is the "reference count of the child" in parent process and how it affects event loops and IPC?

I will try to get this info from somewhere, any links/hints are appreciated.

P.S. I will not be offended if someone will create a PR before me.

**Comment by bnoordhuis** [comment]
@Dzenly Libuv (and therefore node) has a concept of 'handles'.  Handles represents things like timers, TCP sockets, IPC channels, child processes, etc.

Libuv keeps polling for events as long as there are active handles.  But sometimes, you want events for a handle but you don't want it to keep the event loop alive when everything else has already quit.  That's when you unref it (and ref it again if you change your mind.)

In pseudo-code:

``` c
for (;;) {
  refcount = count(active_handles) - count(unrefed_handles);
  if (refcount <= 0) break;
  wait_for_events();
}
```

**Comment by Dzenly** [comment]
Ok, I planning to add such text to the doc:

```
### child.unref()

Removes the child from active handles of the parent's event loop,
allowing the parent to exit independently of the child, unless there is
an established IPC channel between the child and parent.

See also [`options.detached`][] for more details and examples.
```

I would like to add more info.
Say, am I understand correctly that unref() function exists only in ChildProcess object, returned by spawn().
Other child_process methods (especially synchronous ones) do not add ability to unref() child.
Is it true and is it by design?

Also, I don't know workflow how to spread changes in docs to all affected versions of docs.
Say, I created 'docs-issue-104' branch. Then I will commit and push my changes. Then I will do PR.
How this PR will be applied to different docs versions (say 4.x, 6.x, and maybe even for 0.12.x)?
Or it will be applied to 6.x version only?
Where can I find info on this?

**Comment by Dzenly** [comment]
I made a PR with the text mentioned above.
When I will have answers on the questions above, I will made another PR to improve the doc.

**Comment by bnoordhuis** [comment]
> Other child_process methods (especially synchronous ones) do not add ability to unref() child. Is it true and is it by design?

Correct.  What would the point of a .unref() method be for spawnSync() or execSync()?

> How this PR will be applied to different docs versions (say 4.x, 6.x, and maybe even for 0.12.x)?

Target the master branch.  The person who lands it will make sure it gets back-ported to the right branches by tagging it appropriately (e.g. lts-watch-v4.x.)

**Comment by Dzenly** [comment]
I am not sure about the point of presense unref() method for spawnSync()'s child.
I had only misty thoughs about ProcessA which creates ProcessB by spawnSync(), then ProcessB creates
ProcessC via spawn(), detached and unreferenced, and then, ProcessA should .ref() ProcessC().
This is some draft thought, forget it.

But there could be a point for mentioning this in documentation.
The "Sync" suffix here has a specific meaning, comparing with callback - driven modules (e.g. `fs`).
At first time, without proper doc reading, I used spawnSync() and then was surprised why there is no "unref()" method :), then I have to RTFM :).

For now, I think about adding the line: "Note: this method exists in `child` returned by `spawn()` only." for
unref() and ref() doc sections.

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
