### ISSUE TITLE
Readable Stream pipe documentation misleading

### ISSUE THREAD

**Issue by claytongulick** [nodejs/docs#105]
In the docs, the documentation for pipe says:

```
readable.pipe(destination[, options])#

destination <stream.Writable> The destination for writing data
options <Object> Pipe options
end <Boolean> End the writer when the reader ends. Default = true
This method pulls all the data out of a readable stream, and writes it to the supplied destination, automatically managing the flow so that the destination is not overwhelmed by a fast readable stream.
```

This is a bit misleading and it looks like has lead to some confusion around the internet. 

> This method pulls all the data out of a readable stream

Implies that the internal buffer is drained immediately on pipe() and the data forwarded to the destination. In fact, more than one site around the internet says this exact thing. Reviewing the streams source code, this doesn't appear to be technically accurate, since what pipe() really does is broker the io events from the source to the destination.

The reason this matters is that it implies that if you have on("data") and on("end") listeners on the original stream, piping that stream may interfere with the original listeners, which it does not.

In practical terms, I ran across this because I needed to intercept (read) the request stream in express, but also have the normal express middleware process the stream (body-parser). I needed to ensure that piping would be non-destructive to the stream, and based on the docs and other info I read on the internet, that didn't seem to be the case, I almost ended up using an unshift() based solution, which would have been terribly wrong.

Is there a way we can communicate in the docs that pipe() is really safely replicating the io events and not draining the internal buffer?

**Comment by addaleax** [comment]
Do you have a concrete suggestion for improvements, e.g. something along the lines of “This method watches a readable stream for data”? If so, you can definitely create a PR at [nodejs/node](https://github.com/nodejs/node).

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
