### ISSUE TITLE
Documentation recommends readline for splitting a file into lines

### ISSUE THREAD

**Issue by joepie91** [nodejs/docs#107]
After seeing two #Node.js users in two days trying to work the `readline` module into a file processing pipeline (that required splitting the file into lines), I inquired what made them pick this solution, rather than eg. piping a ReadableStream through the `split` module. As it turns out, they were working from [this example code](https://nodejs.org/api/readline.html#readline_example_read_file_stream_line_by_line) in the Node.js `readline` documentation.

Do we really want to be teaching users to use `readline` for splitting up a file? Whereas the custom `line` events of the `readline` module make sense in a "user enters commands one-by-one" scenario, processing a file line-by-line is more of a Transform stream scenario - yet the documentation recommends using `readline` for this, essentially breaking interoperability with the entire streams ecosystem.

I understand that the `split` module is a third-party module, and that the Node.js documentation might want to avoid recommending specific third-party modules (preferring standard-library solutions), but in that case it might be better to just remove this example entirely, as it's evidently not a very good example of how you'd use `readline` in a well-written application. In pretty much every real-world case, you'd want to use a standard Node.js Stream to represent a split file.

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
