### ISSUE TITLE
Node v6.3.1 docs: net.Socket

### ISSUE THREAD

**Issue by zeronone** [nodejs/docs#109]
I am looking at the documentation of `net.Socket` in node v6.3.1.

It says:

> // Event: 'data'
> Emitted when data is received. The argument data will be a Buffer or String. Encoding of data is set by socket.setEncoding(). (See the Readable Stream section for more information.)

> Note that the data will be lost if there is no listener when a Socket emits a 'data' event.

The last line in the documentation mentions about the possibility of data loss. As far as I know, streams3 streams starts with a paused state. So there shouldn't be any data flowing until the first 'data' listener is attached. Is there any exception for net.Socket or am I miss-understanding something.

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
