### ISSUE TITLE
Circular reference for OS Constants

### ISSUE THREAD

**Issue by joepie91** [nodejs/docs#111]
As reported on IRC:

```
[13:46] <ToraxMalu> moin - i found a circular reference in the documentation
[13:46] <ToraxMalu> https://nodejs.org/dist/latest-v6.x/docs/api/os.html#os_os_constants refers back to itself instead on a list of constants
```

([Clickable link](https://nodejs.org/dist/latest-v6.x/docs/api/os.html#os_os_constants))

**Comment by eljefedelrodeodeljefe** [comment]
That is a little quirky, yes. @jasnell without looking at it, that was probably yours? Shall we remove it?

**Comment by addaleax** [comment]
It’s just a broken link, the link should in the `os.html#os_os_constants` should point to `os.html#os_os_constants_1`. @joepie91 Do you want to open a PR with that at nodejs/node?

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
