### ISSUE TITLE
http ClientRequest documentation unclear about inheritance when visually scanning

### ISSUE THREAD

**Issue by fresheneesz** [nodejs/docs#112]
Make it clearer upfront when an object inherits fields from another. I just spent 20 minutes trying to find the docs about an http request object, only to eventually find a small unassuming note that ClientRequest inherits from IncommingMessage. Docs shouldn't be written assuming you're reading them in their entirety. People look for one specific thing in the docs, never read them from start to finish.

**Comment by stevemao** [comment]
@fresheneesz Please send a PR to [the main repo](https://github.com/nodejs/node/pulls). Thanks :)

**Comment by fresheneesz** [comment]
Nevermind, I was reading the docs wrong
