### ISSUE TITLE
Rough Meeting Notes (2016-12-01 @ NINA)

### ISSUE THREAD

**Issue by itspun** [nodejs/docs#114]
Documentation Work group:

Problems:
- 3 guides in different places, nodejs/node, nodejs/docs, nodejs website
- they aren't kept in sync
- no one knows what should be where
- there is a mixture of "guides" for contributors and for users/website presentation
- terminology is confusing (guides, topics, guides for code vs guides for using code)

Proposal:

- nodejs/docs should
  1. have documentation content deleted from it
  2. be renamed to docs-wg (maybe?) to make it clear that this isn't a content repo, but a wg coordination repo

- nodejs/node should
  - contain the API docs
  - contain markdown files with information on how to contribute (test writing, internal howtos)
  - should not contain guides, where guides are information to be consumed of users of node
     - there is one "guide" (timers) and "topics" in nodejs/node:docs/ that are user-facing and
        should be on the website, they should move to nodejs/nodejs.org

- nodejs/nodejs.org
  - this is the website, and currently has "copies" (sporadically maintained) of the guides from nodejs/doc and nodejs/node... it should become the canonical source of website content *other* than API documentation

**Comment by eljefedelrodeodeljefe** [comment]
Sorry, what is this?

**Comment by evanlucas** [comment]
These are meeting notes from Node Interactive in Austin. We are trying to get the docs working group back up and improve the docs.

**Comment by bengl** [comment]
Extra context: current WG members in attendance here in Austin:

* @sam-github 
* @evanlucas 
* @bengl

**Comment by RichardLitt** [comment]
I would have loved to have been a part of this. Any chance of having an online call?

**Comment by gibfahn** [comment]
Non WG people in the meeting: @drzal @mgalexander @greenpioneer @lewisjellis @itspun

**Comment by Qard** [comment]
Sorry I missed this. I was in the VM meetings. I'd like to be involved too though.

I'm in agreement with everything stated in the proposal. However, was there any discussion with CTC on the guides location? They ended up in nodejs/node previously because of concerns with them getting out-of-sync with API docs.

**Comment by evanlucas** [comment]
> However, was there any discussion with CTC on the guides location?

@Qard not officially, no. I think that we are still in the stage where we are trying to come up with the plan to take to the CTC to get the working group moving forward.
