### ISSUE TITLE
Async meetings

### ISSUE THREAD

**Issue by Qard** [nodejs/docs#116]
I feel the docs working group needs some regular discussion around our goals and progress to keep things moving. However, a video call is probably more than is needed. I'm proposing we try async meeting issues on a regular basis where we have a limited time to check in and vote on anything that needs to be voted on. Exact length and frequency would need to be decided, but something like a 24 hour span every 2 weeks would probably work. How does everyone else feel about this? Any objections?

If everyone is on board with this, I'd like to propose a first meeting with an agenda item to define a specific proposal for the guides location to present to the CTC.

**Comment by sam-github** [comment]
I'm OK with trying anything, and we can iterate on the fly, so +1 for me.

I thought the meetings were for discussion though, not voting. Node uses a consensus forming strategy, not a dictatorship of the majority, so I would hope voting would be rare.

Then again, discussion can happen in github.

How would an "async meeting issue" work?

**Comment by Qard** [comment]
Mostly I don't see voting happening. Just thinking for the occasional thing, like the decision we made to do guides/topics stuff back when we started this.

I mainly imagine the async meeting issue being used to coordinate larger tasks, like centralizing the guides/topics location, and to determine what areas to focus on going forward. There's lots of topics and guides that could be written, so we should try to think about what we can do _now_ to make progress there.

**Comment by Qard** [comment]
Also, it could be a good place to just drop suggestions for docs that'd be useful but perhaps the person who thinks of it doesn't have the time or expertise to write it themselves.

**Comment by Qard** [comment]
Not much reaction other than a couple thumbs up. I'll try posting a first meeting issue on Monday and we can try it out. If you have any topics you want to discuss, feel free to post suggestions in advance here.

**Comment by evanlucas** [comment]
It would be cool if we could come up with a solid plan for where we want the guides to live. If we could get that together before Wednesday, I'd be happy to bring it up during the CTC meeting.

**Comment by Qard** [comment]
Our first meeting seems to have worked well. After seeing how the conversation went, I'm thinking we should try a meeting issue every 2 weeks and keep it open for 48 hours.

Drop some 👍 or 👎 on this and if the group seems to agree, I'll get another issue up on Monday the 23rd.
