### ISSUE TITLE
Add @vsemozhetbyt?

### ISSUE THREAD

**Issue by Trott** [nodejs/docs#120]
I know this is already a pretty big group, but maybe consider extending an invitation to @vsemozhetbyt to at least be in the GitHub team so they get notified when someone @-mentions nodejs/docs? They've been doing a ton of work on docs lately.

**Comment by Trott** [comment]
@vsemozhetbyt If you'd like to be added to the docs team, leave a note here or send me an email. I don't want to add you if you're not interested. :-D (And, of course, it's totally OK if you're not interested!)

**Comment by vsemozhetbyt** [comment]
@Trott Thank you for the invitation. I would like to be added if it could help me help the team with the docs) However, please consider this issues:

1. I am not a native speaker and my English is very poor, artificial and full of errors (so I've limited myself to the code examples in the docs in my PRs).
2. I have not much experience in the frontend, so all the nodejs.org stuff (md to html rendering and so on) is somehow scary for me.

If I could be of any help despite these issues and of more help with adding to the team, I would be honored.

**Comment by Trott** [comment]
@vsemozhetbyt Even if all you do is review code samples, that will be a big help. I'll add you and if it proves to be frustrating for you, you can always remove yourself.

(By the way, I don't think you make very many errors in your written English. Certainly, not many more than a native speaker. In fact, fewer than many native speakers! :-D )

**Comment by vsemozhetbyt** [comment]
Thank you) This is due to tireless efforts of the [Grammarly](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen) (and occasionally Word) grammar checker‎)
