### ISSUE TITLE
Meeting #2

### ISSUE THREAD

**Issue by Qard** [nodejs/docs#121]
I meant to post this last week...I blame FFXV. 😨 

Agenda:
- Guides navigation location and accessibility
- Updating the md files in nodejs/docs

If you have any other things to discuss, just say so. 😸

**Comment by Qard** [comment]
For the guides location, should we consider a fully separate part of the website, or even an entirely different subdomain? I quite like the book structure of the [Rust](https://www.rust-lang.org/en-US/documentation.html) docs.

As for the md files, those are looking rather out-of-date. Anyone else care to review them and comment on what they'd like added or changed? Some additions to CONTRIBUTING.md to reflect the new guides location would be good. It might be good to split that doc up into a bunch of separate files too.

**Comment by kahwee** [comment]
I agree guides should be a separate part. I was browsing the new [Webpack](https://webpack.js.org/guides/) website and they have a whole bunch of guides that just grew organically over time. 

There's docs which is highly ordered which content structure can be determined ahead of time. And then there's guides which is we may not know how to structure the articles to make it easy to find. We probably have to refine the content structure to keep them relevant. 

Giving guides its own section allows that growth. Maybe a different repository would even work better.
