### ISSUE TITLE
descriptions of "The module Object"'s property are not clear

### ISSUE THREAD

**Issue by stevemao** [nodejs/docs#122]
[At the end of the modules page](https://nodejs.org/dist/latest-v7.x/docs/api/modules.html#modules_module_id), the descriptions are too terse and not so clear in my opinion.

EG: 

> module.id
The identifier for the module. Typically this is the fully resolved filename.

When is it not the fully resolved filename?

> module.loaded
Whether or not the module is done loading, or is in the process of loading.

When it is in the process of loading, does it return `true` or `false`?

> module.require(id)

What is the difference between `module.require(id)` and the "global" `require()` is not so clear. I think concrete code examples would be better. Thanks!

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
