### ISSUE TITLE
http.ClientRequest is missing some methods

### ISSUE THREAD

**Issue by catdad** [nodejs/docs#125]
In the class definition of http.ClientRequest, it says the following:

> The header is still mutable using the `setHeader(name, value)`, `getHeader(name)`, `removeHeader(name)` API.

This suggests that instances of the class have those 2 methods. However, there is no documentation for these 3 methods in the list of methods for this class.

Reference: https://nodejs.org/dist/latest-v7.x/docs/api/http.html#http_class_http_clientrequest

**Comment by sam-github** [comment]
Confirmed, ClientRequest inherits from OugoingMessage, and it and its methods are not documented .

**Comment by sam-github** [comment]
cc: @nodejs/http

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
