### ISSUE TITLE
Package documentation (how to intl)

### ISSUE THREAD

**Issue by martinheidegger** [nodejs/docs#126]
Hello Docs team 👋

In the last [hangout of the intl wg](https://github.com/nodejs/Intl/issues/40) we talked about "how to store & implement translations of error messages" and I felt like this issue is the perfect to prepare a guide on _"how to write a package with i18n support"_ with Node.js being the first adopter of the best-practices. Now we have been wondering where to put those suggestions. Of course we could just place a markdown file in the intl-repo but then it might fall out of any translation work done.

Where would you put this sort of information?

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
