### ISSUE TITLE
Decharter this Working Group?

### ISSUE THREAD

**Issue by jasnell** [nodejs/docs#127]
The Documentation Working Group has been inactive for quite some time. I have opened a proposal in the CTC repository to decharter the group. The nodejs/documentation team would still exist, but this repository would be archived and the responsibilities assigned to the Documentation Working Group would be folded back into the CTC's area of responsibility.

Refs: https://github.com/nodejs/CTC/pull/121

**Comment by eljefedelrodeodeljefe** [comment]
Yes, please. I was writing what was needed (mandating and so on), apart from actual user activity. Both have not happened, despite resurrection tries. It's time...

Maybe someone will come around with a good idea, or stars in the core repo align desperate need of fundamentally better docs at some point.

Docs are generally working well at the moment even without the explicit WG.

**Comment by mikeal** [comment]
It's worth noting that a ton of documentation *is* being written and iterated on, this WG just isn't directly involved :)

**Comment by eljefedelrodeodeljefe** [comment]
No doubt, looking at the commit log. Noted also above.

**Comment by benjamingr** [comment]
LGTM, unless a CTC member wants to step up and lead the group it's pointless to keep alive and lots of good six work happening anyway

**Comment by Qard** [comment]
I'm good with dechartering. We're only really working on writing and review docs at this point, which is more a team activity than a working group activity. We can always recharter again in the future, if a need arises.

**Comment by Knighton910** [comment]
@Qard +1

**Comment by gibfahn** [comment]
Given that https://github.com/nodejs/CTC/pull/121 landed, this repo should probably be archived now.

Is that just a case of changing the name to `docs-archive` and changing the README?
