### ISSUE TITLE
Better wording for modules_all_together

### ISSUE THREAD

**Issue by buckle2000** [nodejs/docs#128]
In here:
https://nodejs.org/api/modules.html#modules_all_together

IMHO,
please change
```
require(X) from module at path Y
1...
2...
3. If X begins with './' or '/' or '../'
   a. LOAD_AS_FILE(Y + X)
   b. LOAD_AS_DIRECTORY(Y + X)

LOAD_AS_DIRECTORY(X)
1...
2. LOAD_INDEX(X)
```
into
```
require(X) from module at path Y
1...
2...
3. If X begins with './' or '/' or '../'
   a. LOAD_AS_FILE(Y + X)
   b. LOAD_AS_DIRECTORY(Y + X)
   c. LOAD_INDEX(Y + X)

LOAD_AS_DIRECTORY(X)
1...
```
which is less nested thus easier to understand.

**Comment by stevemao** [comment]
@buckle2000 Could you give more details? Why is it more conventional? What do you mean by that?

**Comment by buckle2000** [comment]
In current description of [this](https://nodejs.org/api/modules.html#modules_all_together), `LOAD_INDEX` is nested in `LOAD_AS_DIRECTORY`, which is unnecessary and seems confusing (at least to me).

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
