### ISSUE TITLE
Improve the words usage in socket.setTimeout() definition

### ISSUE THREAD

**Issue by surajwy** [nodejs/docs#131]
Refer following lines from net.js `socket.setTimeout` function: 
1. Sets the socket to timeout after timeout milliseconds of **inactivity** on the socket.
2. When an **idle** timeout is triggered the socket will receive a 'timeout' event but the connection will not be severed.
3. If timeout is 0, then the existing **idle** timeout is disabled.

We should be more clear and explicit about what **inactivity** and **idle** means.

This setting means two things based on following cases:
case 1: If the connection is not established, then we timeout after supplied time. Right now this message is not at all conveyed in the definition.
case 2: If the connection is established but is idle, then we timeout after supplied time

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
