### ISSUE TITLE
Internal doc guide: introducing larger features

### ISSUE THREAD

**Issue by chrisdickinson** [nodejs/docs#23]
It would be handy to have a guide that introduced "how to introduce large features into Node". It should touch on the planning process, review, and bits of implementation — for example, the use of feature flags to gate access.

**Comment by Qard** [comment]
Sounds good. As part of it, we should try to identify what _should_ actually be made into a PR and what is more suitable for userland.

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
