### ISSUE TITLE
Missing Error Documentation

### ISSUE THREAD

**Issue by samholmes** [nodejs/docs#26]
In my experience, Node.js will report many errors like EACCESS, EPIPE, etc. No where are these errors documented (what they mean and when they occur). This seems like a big issue.

Why it's a pretty significant issue is because errors is one of the most common thing developers must handle, and a vague error is the worst kind of error. I believe Node.js can do better; I think every error from Node.js core framework should be documented and explained.

PS: This is a duplication of the original issue for nodejs.org https://github.com/nodejs/nodejs.org/issues/162#issuecomment-125762762

**Comment by sam-github** [comment]
I believe this issue to have been fixed already in io.js, have you seen https://iojs.org/api/errors.html#errors_common_system_errors ?

**Comment by Qard** [comment]
Indeed, when a converged node build lands, the updated API docs should also land on the nodejs.org website. In the meantime, that page could be backported. I don't see anything there unique to io.js.

**Comment by Fishrock123** [comment]
As already noted, they were documented months ago by @chrisdickinson: https://iojs.org/api/errors.html
