### ISSUE TITLE
Kickoff Meeting [2015-09-18 20:00 UTC]

### ISSUE THREAD

**Issue by bengl** [nodejs/docs#30]
At the Node.js Collaborator Summit, it was decided that a Documenation Working Group meeting needs to happen.

So let's do it.
### Date and Time

Aug 18th, 2015, at 20:00 UTC. ([See this in your local time zone.](http://www.timeanddate.com/worldclock/fixedtime.html?iso=20150818T2000))
### Participating

Participant link: https://plus.google.com/hangouts/_/hoaevent/AP36tYeG3AQAvPNE5qmWKaTc-2s7DgxyhV-MelM43peyBHJhC84DZg

Link to watch: http://www.youtube.com/watch?v=Z-nYI5Q5myM

Minutes Doc (will be in repo after meeting): https://docs.google.com/document/d/1Q1HyzOf-kjx2giZgSzg5hTY8omieux5mQRykwLHboxU/edit?usp=sharing

Email me (bryan@bryanenglish.com) if you want edit access to the minutes doc.
### Potential Attendees
- @chrisdickinson
- @drewfish
- @Qard
- @sam-github
- @danielkhan
- @distracteddev 
- @bengl
- @snostorm

Please comment here if you're interested in attending and your name's not here.
### Tentative Agenda
- Intros
- Governance
- Build/Website Integration
- API Docs from core into this repo?
- Overview of current open PRs.

If you'd like to add further topics, please mention so in comments.

**Comment by drewfish** [comment]
The doodle doesn't say — a 1-hour meeting?

**Comment by bengl** [comment]
Yes, a limit of 1 hour.

**Comment by sam-github** [comment]
I'm away all next week. One of the other things that came up at the summit was trying to give more time to schedule meetings :-) I think all proposed dates should be at least a week from now, to give people time to put things in their calendar.

**Comment by bengl** [comment]
@sam-github Oops! I had definitely meant to do one week later than that. For some reason I thought we were still in July. Sorry!

In light of that, I've edited the Doodle and the description here.

**Comment by snostorm** [comment]
I'm interested in attending

**Comment by bengl** [comment]
Based on the Doodle, let's do this on Aug 18th at  20:00 UTC. ([See this in your local time zone.](http://www.timeanddate.com/worldclock/fixedtime.html?iso=20150818T2000))

Participant link: https://plus.google.com/hangouts/_/hoaevent/AP36tYeG3AQAvPNE5qmWKaTc-2s7DgxyhV-MelM43peyBHJhC84DZg

Link to watch: http://www.youtube.com/watch?v=Z-nYI5Q5myM

**Comment by bengl** [comment]
Here's a minutes doc: https://docs.google.com/document/d/1Q1HyzOf-kjx2giZgSzg5hTY8omieux5mQRykwLHboxU/edit?usp=sharing

If you want edit access and I haven't given it to you already, please email me (bryan@bryanenglish.com).

**Comment by danielkhan** [comment]
I was on vacation and just watched the video and just want to add my 2 cents here. Not knowing where the API docs topic went by now I just want to ask if we couldn't learn from other projects here. Looks like a quite common problem.
For instance PHP really has excellent docs (http://svn.php.net/viewvc/phpdoc/en/trunk/).

Maybe this is a naive approach but to me continuously extracting the function headers and parameters along with the hopefully existing API docs into a directory and file structure that basically creates stubs for a more verbose documentation looks like a good option. 
Maybe it would be possible to create some kind of follow up issue on what's the current state of affairs now.

**Comment by bengl** [comment]
Closing this. Meeting happened and minutes are in #57.
