### ISSUE TITLE
Document header over-writing versus joining

### ISSUE THREAD

**Issue by bengl** [nodejs/docs#32]
[This](https://github.com/nodejs/io.js/blob/master/lib/_http_incoming.js#L122-L126) doesn't appear to be explained in the HTTP API docs. It should be there for clarity. For the moment, it seems that this comment in the source seems to be the only place it's mentioned.

**Comment by drewfish** [comment]
I believe the HTTP incoming headers merge/overwrite algorithm changed between 0.10 and 0.12.
https://github.com/joyent/node/commit/51bd1b4483f60d85ee19274aab98505a0b5c9105

**Comment by bengl** [comment]
This is handled by https://github.com/nodejs/node/commit/4008961a07b5ea904273b89122ad8825f2593a53. Closing.
