### ISSUE TITLE
Cannot find 'Event: data' or 'Event: error' in the table of contents.(api/http.html)

### ISSUE THREAD

**Issue by liuzeyafzy** [nodejs/docs#40]
When I use _http.request_, I can get  an instance of the _http.ClientRequest_ class. Also I need handle error event like this:

```
req.on('error', function(e){
  console.log('Error: ' + e.message);
});
```

However, no _Event: error_ in _http.ClientRequest_.
The same to _Event: data_ in _http.IncomingMessage_.

**Comment by sam-github** [comment]
You are right about error, though error is often not explicitly documented, its a bit special. Should be there, though. Can you submit a PR?

For IncomingMessage, you missed that it's a ReadableStream, follow that link, it documents the 'data' event.

**Comment by liuzeyafzy** [comment]
@sam-github Thanks for your help.
I`m not ready to submit a PR.

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
