### ISSUE TITLE
Migrate content files to new.nodejs.org?

### ISSUE THREAD

**Issue by Qard** [nodejs/docs#44]
There seems to be a disconnect between the website and the docs wg. I feel like it'd help to merge our content files into https://github.com/nodejs/new.nodejs.org and do all future documenting there, using this repo purely for communication and documenting the _process_ of contributing docs. Does anyone have any strong opinions here?

I'd be happy to do the migration, if we want to go forward with it. It'd mainly just be a matter of dumping files into https://github.com/nodejs/new.nodejs.org/tree/master/locale/en/docs and adding some yaml headers to things.

@nodejs/documentation @nodejs/website

**Comment by bengl** [comment]
I think I'm +1 on this.

This would make the process for making our new docs available/published much more streamlined. I think the existing process for document inclusion and review can happen in the website repo, especially if @nodejs/documentation [gets write access there](https://github.com/nodejs/new.nodejs.org/issues/205).

Based on activity (though not necessarily time), this WG and repo are still brand new, so now's a great time to make this kind of a move if we're going to.

**Comment by Qard** [comment]
Yep, my thoughts exactly. We've got a handful of docs written and no clear process on how to merge changes as a separate repo. As a single repo it's a lot clearer, and we can use this repo to further clarify the process. :smile_cat:

**Comment by chrisdickinson** [comment]
SGTM!

**Comment by phillipj** [comment]
Sounds awesome, much appreciated :+1:

**Comment by Qard** [comment]
As you can no doubt see above, I've created some issues to port our content files over to new.nodejs.org. If/when those are merged, I'll put together a PR to remove that stuff from this repo.

**Comment by chrisdickinson** [comment]
I think (per https://github.com/nodejs/node/pull/4244#issuecomment-169562193) we're looking at working primarily in the Node repo now, and getting that to a place where we can produce internationalized docs for the website WG to consume.

**Comment by bengl** [comment]
This stuff has all been moved now. All that remains is to remove the existing content directories from this repo. I'll leave this open until that's done.

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
