### ISSUE TITLE
Docs WG Meeting #2 - 2016-01-20 @ 10:00AM PST

### ISSUE THREAD

**Issue by bengl** [nodejs/docs#52]
Time for another meeting.

This meeting is scheduled for 2016-01-20 @ 10:00AM PST, and will be a public-viewable [Google Hangout on the Air](https://plus.google.com/u/0/events/cffe0t2oigh3kvk54bh3p0q7tbs).

If you participated in the Doodle poll, then your Github username should be in this list, and you should have received an invite. If not, and you want to participate, please email me (bryan@bryanenglish.com).

Minutes will be recorded in [this Google Doc](https://docs.google.com/document/d/1hs1gf1DK6ek5Lp5WWZOOOKTN52lbDZZcXUrOlWbhfUY) and then committed back to this repo after the meeting. Please let me know if you want write access to the doc.
### Participants
- @chrisdickinson 
- @TheAlphaNerd 
- @benjamingr 
- @evanlucas 
- @qard
- @distracteddev 
- @bengl
### Agenda
- #50 WG Ratification

**Comment by benjamingr** [comment]
Who is invited?

**Comment by chrisdickinson** [comment]
@benjamingr We're inviting all current Docs WG members, as well as any collaborators (or website WG members) that have committed to the `docs/` directory on nodejs/node within the last six months.

**Comment by bengl** [comment]
@nodejs/documentation if you haven't yet put your availability for the meeting into the doodle, please do so. http://doodle.com/poll/8weupkr8x9kaetdd

**Comment by bengl** [comment]
@nodejs/documentation reminder, this meeting is today at 10AM PST. Please let me know if you don't have the hangout link.

**Comment by benjamingr** [comment]
@bengl I don't have the hangouts, my email is benjamingr at gmail dot com

**Comment by bengl** [comment]
@benjamingr sent

**Comment by MylesBorins** [comment]
I don't have the hang outs link either :S
