### ISSUE TITLE
Docs WG Sign-up Round #2

### ISSUE THREAD

**Issue by chrisdickinson** [nodejs/docs#63]
Hey folks! If you're interested in joining the Docs WG — or in helping out with the Node docs in general, leave your name here. We'll onboard folks on a regular basis. Thanks!

(Previously: #2)

**Comment by techjeffharris** [comment]
I would like to help however I can!

**Comment by tomgco** [comment]
I am up for helping out!

**Comment by ashleygwilliams** [comment]
hello! i am definitely interested and already working to start collaboration between this working group and @nodejs/inclusivity :)

**Comment by jasisk** [comment]
I'm in to help out.

**Comment by chrisdickinson** [comment]
OK! I've invited the following people to Slack and the Docs GitHub team:
- @ashleygwilliams
- @danjenkins
- @kahwee
- @kelthenoble
- @techjeffharris
- @tomgco

I've used the email address associated with your GitHub profile. If I haven't invited you, don't fret — it's most likely because I haven't been able to find an email for you. Please email me at `christopher.s.dickinson at gmail dot com` and I'll get you added. Thanks! :tada:

**Comment by estliberitas** [comment]
I would like to participate. :-)

**Comment by stevemao** [comment]
+1 @estliberitas :smile:

**Comment by thefourtheye** [comment]
I myself wanted to recommend @estliberitas :)

**Comment by jinglish** [comment]
I'd love to help out. `joseph dot inglish at gmail dot com`

**Comment by eljefedelrodeodeljefe** [comment]
This can be closed, right? @estliberitas have you been added already? If not let's proceed with a PR.

**Comment by stevemao** [comment]
@eljefedelrodeodeljefe I don't think any new members are added.

**Comment by eljefedelrodeodeljefe** [comment]
Hmm, okay. Then I reopen this, sorry.

**Comment by estliberitas** [comment]
@eljefedelrodeodeljefe not yet

**Comment by estliberitas** [comment]
@eljefedelrodeodeljefe making PR

**Comment by stevemao** [comment]
This can probably be closed now :)

@eljefedelrodeodeljefe ?

**Comment by RichardLitt** [comment]
Why would you close it? What about new people who want to join? 

I would like to join the working group.

**Comment by eljefedelrodeodeljefe** [comment]
Closing this as I believe everyone has made it into the list. @RichardLitt we would have a another issue for you (and others) after resolution of this https://github.com/nodejs/CTC/issues/32.
