### ISSUE TITLE
outreach: want do promote doc WG at reddit etc.

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [nodejs/docs#65]
cc/ @chrisdickinson 

Even though it might not sound too sexy to contribute / express opinion to / about docs, I want to promote this thing, say at `reddit`. Catch phrase: "there is a doc WG now, please contribute / tell your opinion. We want to be the best docs out there". Does that seem valid to you?

**Comment by chrisdickinson** [comment]
Totally — once we land the ROADMAP (in whatever form it takes) we'll definitely want to circulate it to give interested folks an idea of where we need help!

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
