### ISSUE TITLE
internal doc guide: a tour through node

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [nodejs/docs#71]
I was writing up a piece, that should give new comers and example work through of how node is built and how you can traverse the stacks. It is doing this by introducing a new feature `hello_world` from scratch  (I continued working of extending `path` though) with having `v8`, `libuv`, `js` code and hooking it into the build system. 

It was missing some parts at the `libuv`-to-`v8` level and explanations how reading in `js` strings with `vm` works. With some senior support I could actually be able to complete this. 

Does that sound interesting in terms of the roadmap? #70. Also might touch the current issue of nodejs/node#4931

**Comment by thefourtheye** [comment]
Well, you can always ask, if you have any questions, in the IRC channel :-)

**Comment by eljefedelrodeodeljefe** [comment]
Sure. I was just wondering whether that would be an interesting guide topic.

**Comment by Qard** [comment]
:+1: I'd like to see this. Let me know if you need any help. :smiley_cat:

**Comment by chrisdickinson** [comment]
This would be excellent!

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
