### ISSUE TITLE
Create overview for "Blocking vs. non-blocking"

### ISSUE THREAD

**Issue by jrit** [nodejs/docs#77]
I'm raising my :hand: to write the overview article which was called out in this quarter's roadmap https://github.com/nodejs/docs/pull/70 - I believe my understanding is good enough from previous writing I've done on the topic.

A PR on the event loop is currently open at https://github.com/nodejs/node/pull/4936 and because of the relationship between the event loop and blocking, my plan is to start on the "Blocking vs. non-blocking" overview but ultimately make sure the event loop PR is merged first and be sensitive to unnecessary overlap.

@chrisdickinson @techjeffharris sound ok to you?

**Comment by chrisdickinson** [comment]
This sounds good to me — I'll add this issue to the roadmap. Thanks!

**Comment by techjeffharris** [comment]
Sorry for the delay!  By all means, please do!  :)

**Comment by eljefedelrodeodeljefe** [comment]
Happening at nodejs/node#5326

**Comment by jrit** [comment]
landed in https://github.com/nodejs/node/commit/5f1eb434ee750abbd18a25d3b978eb8828f6d1dc
