### ISSUE TITLE
meta: style guide

### ISSUE THREAD

**Issue by a0viedo** [nodejs/docs#80]
This is a continuation of https://github.com/nodejs/docs/pull/79, I've noted that there're a few styles not following (that I know of) explicit conventions.

The ones I could came up with:
- what to use when refering to different values (how to format strings, how to format booleans, etc). Example: the [Buffer docs](https://github.com/nodejs/node/blob/master/doc/api/buffer.markdown) uses `'true'` to reference a boolean value once but mostly uses just `true`.
- markdown used when adding code blocks (i.e. object literals, JSON). Relevant discussion https://github.com/nodejs/node/pull/4733

I'm missing any?

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
