### ISSUE TITLE
[Question] Why there is that gradient background at the bottom of the sidebar?

### ISSUE THREAD

**Issue by ghost** [nodejs/docs#81]
![2016-02-08 11 21 07](https://cloud.githubusercontent.com/assets/2175645/12899736/8cba2752-cebb-11e5-85cf-23993209f3bc.png)

I'm sorry, but it looks so ugly...

**Comment by a0viedo** [comment]
@dkfiresky is that nodejs.org? I think https://github.com/nodejs/nodejs.org is the WG you're looking for. Also might want to include browser info.

**Comment by stevemao** [comment]
@dkfiresky When you open an issue there, make sure you provide information about:
1. what browser you are using
2. what page you are on
3. any information that we need to be aware
Thanks a lot.

**Comment by ghost** [comment]
@stevemao why did you closed this issue?
here some info:
1. Safari latest version (I think it's 9) (OS X El Capitan)
2. https://nodejs.org/dist/latest-v5.x/docs/api/
3. On Google Chrome (Windows 7) the gradient is on top of the scrollbars.

**Comment by stevemao** [comment]
We already said create an issue at https://github.com/nodejs/nodejs.org

**Comment by ghost** [comment]
But it's related to the docs anyway...
