### ISSUE TITLE
Debugger Guide

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/docs#83]
this could be very useful. Perhaps we can build this out as we test and fix the debugger

/cc @Trott

**Comment by jsatk** [comment]
Thanks @TheAlphaNerd. Agreed. 

One issue I struggle with is understanding how to use the `debugger` in a real-world environment. Most of the guides I've found via Google searches have basic and trivial examples that don't map to what a production node app looks like. Especially when tools like grunt and gulp are in the mix. That might be outside of the scope of what this issue would attempt to resolve. But any additional information on how to use `debugger` statements in a node app would be super beneficial.

**Comment by Knighton910** [comment]
Sounds good. I think it's worth exploring.

**Comment by trevnorris** [comment]
@jsatk May also be useful to include documentation on debugging w/ `gdb` or similar. Say there's a lot of external memory allocations, if they're generated in JS then node's debugger is enough. But if they come from, say, an incoming connection, then it's useful to do something like `rbreak node::Buffer::New.*` and get the stack. e.g.

```
(gdb) bt
#0  0x0000000000dee314 in node::Buffer::New(node::Environment*, char*, unsigned long) ()
#1  0x0000000000e3030a in node::crypto::RandomBytesCheck(node::crypto::RandomBytesRequest*, v8::Local<v8::Value>*) ()
#2  0x0000000000e30392 in node::crypto::RandomBytesAfter(uv_work_s*, int) ()
```

Here we can see that the call to create the Buffer originated with `crypto.randomBytes()`. Then we can enter node's debugger and break on `randomBytes()` usage to get more information.
