### ISSUE TITLE
clarify options of api/url.html#url_url_format_urlobj

### ISSUE THREAD

**Issue by mh-cbon** [nodejs/docs#85]
Hi,

small suggestions before a possible PR,

`host`: it should be noted it expects a string like `host:port`
`auth`: it should be noted it expects a string like `user:password` without b64 encoding

`href`, `path` should be moved down in order to not confuse with `pathname` which is the one that matters.

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
