### ISSUE TITLE
What is the state of nodejs/doc-tool?

### ISSUE THREAD

**Issue by Qard** [nodejs/docs#86]
There have been changes happening to the doctool directly in the https://github.com/nodejs/node/ repo, but there is also a copy of the doctool living at https://github.com/nodejs/doc-tool/ which appears to have been largely abandoned. Should we be copying changes back to the doc-tool repo? Moving development there? Deleting that repo?

**Comment by kahwee** [comment]
I'm starting to be convinced that the doc tool need to be externalized. What's the context of having the `node_modules` checked into `node` git `tools/doc`?

**Comment by stevemao** [comment]
ping @nodejs/documentation 

@rvagg incase you didn't see this :)

**Comment by benjamingr** [comment]
This should be brought up at the next meeting. I like the idea of externalizing it better.

**Comment by eljefedelrodeodeljefe** [comment]
We could follow https://github.com/nodejs/citgm 's very good example

**Comment by Knighton910** [comment]
+1 This should be brought up at the next meeting

I agree with @benjamingr this sounds meeting worthy. And i kinda like them where they are. 
It seems convenient. 
@nodejs/documentation Let's weigh in more thoughts.

**Comment by chrisdickinson** [comment]
Externalizing it is probably not worthwhile — we're working to replace it with `remark`, which is a public package.

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
