### ISSUE TITLE
build: provide guide for compiling node binary with optimizations

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [nodejs/docs#88]
See this discussion https://github.com/nodejs/node/issues/2948

First we would need to collect a list of optimization options and derive some tactics from it. E.g. some configurations won't pass tests.
## Options (WIP)
- (use musl)
- disable `openssl`
- use a shared `zlib`
- no `icu`: `--with-intl=none`
- go wild with `strip`
- compile a 32-bit binary
- (...)

**Comment by Knighton910** [comment]
:+1: good start.

**Comment by eljefedelrodeodeljefe** [comment]
Dragging in @TheAlphaNerd here: How open (or secretive) is the release building process? Is it even part of the tasks of the release group or does jenkins do it all? 
I think it might be interesting to add this here, as it could also aid testing. E.g. I still don't know how to properly build on windows, so I can test or alter `.msi`s or build with some of the optimizations. Release building could be somewhat related.

**Comment by MylesBorins** [comment]
The release process is all public :smile:

https://github.com/nodejs/node/blob/master/doc/releases.md

But I think there is now limited access to the release CI

**Comment by eljefedelrodeodeljefe** [comment]
Ah. Thanks for pointing at it. Haven't found what I was looking for though :)

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
