### ISSUE TITLE
Order of events in the process docs

### ISSUE THREAD

**Issue by benjamingr** [nodejs/docs#89]
Hey, I noticed events in the process docs (at https://nodejs.org/api/process.html ) are ordered alphabetically. In my opinion it makes more sense to put related events - namely `unhandledRejection` and `rejectionHandled` - one above the other. It would improve discoverability.

I just wanted to bring this up before making a pull request to know if anyone has any strong objections to it.

**Comment by MylesBorins** [comment]
there was a move not too long ago to alphabetize the docs

Your point is not unreasonable though... there is a lot of value to keep similar cognitive things close to each other. This could be a big churn though to do across the entire docs, and tougher to maintain than simply alphabetized.

I'm open to the idea though

**Comment by chrisdickinson** [comment]
It might best to solve this as a "process promise events" overview doc that links into the reference docs (vs. rearranging the reference docs again.)

**Comment by Qard** [comment]
I'm leaning towards leaving the docs as they are and, as @chrisdickinson said, use guides to point people in the right direction. One could make a similar ordering argument about streams docs, putting `data` after `close` and such, but that's really more indicative of a need for a guide rather than reordering of the reference.

**Comment by benjamingr** [comment]
I tend to agree - what about a "using promises with Node" guide that covers _only_ the caveats, the events and so on? 

(That is, not a promises tutorial - just a "this is how you'd use promises in NodeJS" with mentions of the events)

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
