### ISSUE TITLE
Dash vs colon on style guide

### ISSUE THREAD

**Issue by claudiorodriguez** [nodejs/docs#90]
Going off https://github.com/nodejs/node/pull/5677 and https://github.com/nodejs/node/issues/5672 I think it might be a good idea to add an item to the style guide clarifying where to use colons as opposed to dashes, e.g. colons to separate argument name and type from description, etc.

P.S: I mean the specific instances where we could draw a definite standard - the one that comes to mind is enumeration lists in general, there might be others.

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
