### ISSUE TITLE
Edit in GitHub

### ISSUE THREAD

**Issue by benjamingr** [nodejs/docs#91]
Addressing https://github.com/nodejs/node/pull/4129 which has been open for a while now.

Do we want an "Edit on GitHub" button or not?

**Comment by eljefedelrodeodeljefe** [comment]
Having heard of this for the first time, I'd initially say yes. Reading up on the ticket I agree to Ben though.

**Comment by benjamingr** [comment]
Yeah, I'm also -1 on this.

**Comment by Knighton910** [comment]
`-1`
