### ISSUE TITLE
doc: automated surface testing 

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [nodejs/docs#93]
@mikeal, @chrisdickinson: I wanted to push forward some automated, selenium based testing for the docs (not sure this is living somewhere else already). Is it possible to register at [saucelabs](https://saucelabs.com/opensauce/) or [browserstack](https://www.browserstack.com/pricing) free for open source? I'd start by running some easy screen grabs generated by some script.

This issue would then serve as kick-off for the related tasks.

**Comment by benjamingr** [comment]
Browserstack is free for open source, usually they ask you to place a link saying that the site is tested with browserstack at the readme or the site - for Node I'm sure any mention would do. 

I can email the person who gave us the free account for bluebird and ask.

**Comment by eljefedelrodeodeljefe** [comment]
Both are. Ideally we had both. They require to register, which I wanted to be done by one official representative.

**Comment by stevemao** [comment]
> Ideally we had both.

@eljefedelrodeodeljefe Any reason why we need both?

**Comment by jrit** [comment]
@eljefedelrodeodeljefe is there an open list of items to validate there? I'm looking into adding accessibility validation ref https://github.com/nodejs/nodejs.org/issues/552 so tying onto browserstack could make more sense than a dependency on Phantom

**Comment by eljefedelrodeodeljefe** [comment]
@stevemao jsut for the freedom of choice for the one person implementing it and maybe to mitigate expectations of those companies to land their logo on the website (dunno?)

@jrit no plans yet, but let's head over to nodejs/node#5955 and collect some ideas

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
