### ISSUE TITLE
Document `GLOBAL` or deprecate with warning.

### ISSUE THREAD

**Issue by wheresrhys** [nodejs/docs#94]
The docs only mention lowercase `global` https://nodejs.org/api/globals.html#globals_global, despite `GLOBAL` also being an alias for it.

It seems like React or webpack, or some plugin, [doesn't support use of `GLOBAL`](https://github.com/wheresrhys/fetch-mock/issues/79), which they can be forgiven for doing given that it's not documented.

What is the status of `GLOBAL`? Is it deprecated (and therefore its use should ideally trigger a warning) or supported, in which case it should be documented?

**Comment by evanlucas** [comment]
Hi @wheresrhys. Thanks for opening the issue. As of now, `GLOBAL` is deprecated on the master branch (https://github.com/nodejs/node/blob/master/lib/internal/bootstrap_node.js#L215-L232). At this point, I do not believe it should be documented as it will be removed in the future.

Thanks!

**Comment by wheresrhys** [comment]
Thanks for the answer. IMHO I still think it wouldn't do any harm to document it as deprecated, but good to see you're going to start emitting warnings soon.
