### ISSUE TITLE
CI job to build / host docs

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/docs#95]
When people submit changes such as https://github.com/nodejs/node/pull/6100 for broken links it would be really great if we could run a CI job to quickly build the docs and host them. This would speed up the process of multiple reviewers, and allow people to review without having to build the docs locally

**Comment by stevemao** [comment]
In my own repo, https://github.com/stevemao/awesome-git-addons, there are two bots hit me:
- https://github.com/dkhamsing/awesome_bot
- https://github.com/dkhamsing/frankenstein

issues:
- https://github.com/stevemao/awesome-git-addons/issues/5
- https://github.com/stevemao/awesome-git-addons/pull/4

`frankenstein` can open a pull request to update README links based on HTTP redirects
`awesome_bot` checks for valid URLs in a file, it can be used to verify pull requests updating a README.

Should be easy to be integrated with our existing CI.

**Comment by kahwee** [comment]
Is this a generic bot to build docs rather than just for checking if the links are valid?
