### ISSUE TITLE
notes: handle increasing amounts of notes (that are very specific)

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [nodejs/docs#98]
cc @benjamingr 

We are seeing a lot of platform specific notes or refinement of docs (primarily additions) that reason about platform specific behaviours of methods. This might be too much for newcomers to `node`. In order to handle this we should
1. have a policy for that
2. ease this technically (e.g. by having added dimension of collapsable html)

**Comment by benjamingr** [comment]
I think easing it technically is good. 

I think the notes themselves are definitely a welcome and important addition, I think we should collapse them sans the first sentence by default. Other than placing them with `[1]`s and so on in the footer (which I think we'd rather avoid) I have no other ideas.

**Comment by eljefedelrodeodeljefe** [comment]
Ah, with notes I rather meant `_NOTE: text here_` blocks.

**Comment by benjamingr** [comment]
Yeah, me too.

**Comment by Trott** [comment]
Closing as this repository is dormant and likely to be archived soon. If this is still an issue, feel free to open it as an issue on the [main node repository](https://github.com/nodejs/node).
